"use client";
import React, { createContext, useState, useEffect } from "react";
export const DataContext = createContext();

import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Task Management System",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const tasksListData = [
    {
      client_name: "Michelle Mwangi",
      client_email: "michellemwangim@gmail.com",
      client_phone: "0700562291",
      company_name: "Sensei",
      client_location: "MasaiMara",
      preferred_contact_method: "Email",
      category: "Technical Issue",
      platform_service_product: "Service",
      severity: "Critical",
      issue_description: "this is the details of the issue / task",
    },
    {
      client_name: "Michelle Mwangi",
      client_email: "michellemwangim@gmail.com",
      client_phone: "0700562291",
      company_name: "Sensei",
      client_location: "MasaiMara",
      preferred_contact_method: "Email",
      category: "Technical Issue",
      platform_service_product: "Service",
      severity: "Critical",
      issue_description: "this is the details of the issue / task",
    },
    {
      client_name: "Michelle Mwangi",
      client_email: "michellemwangim@gmail.com",
      client_phone: "0700562291",
      company_name: "Sensei",
      client_location: "MasaiMara",
      preferred_contact_method: "Email",
      category: "Technical Issue",
      platform_service_product: "Service",
      severity: "Critical",
      issue_description: "this is the details of the issue / task",
    },
    {
      client_name: "Michelle Mwangi",
      client_email: "michellemwangim@gmail.com",
      client_phone: "0700562291",
      company_name: "Sensei",
      client_location: "MasaiMara",
      preferred_contact_method: "Email",
      category: "Technical Issue",
      platform_service_product: "Service",
      severity: "Critical",
      issue_description: "this is the details of the issue / task",
    },
    {
      client_name: "Michelle Mwangi",
      client_email: "michellemwangim@gmail.com",
      client_phone: "0700562291",
      company_name: "Sensei",
      client_location: "MasaiMara",
      preferred_contact_method: "Email",
      category: "Technical Issue",
      platform_service_product: "Service",
      severity: "Critical",
      issue_description: "this is the details of the issue / task",
    },
    {
      client_name: "Michelle Mwangi",
      client_email: "michellemwangim@gmail.com",
      client_phone: "0700562291",
      company_name: "Sensei",
      client_location: "MasaiMara",
      preferred_contact_method: "Email",
      category: "Technical Issue",
      platform_service_product: "Service",
      severity: "Critical",
      issue_description: "this is the details of the issue / task",
    },
    {
      client_name: "Michelle Mwangi",
      client_email: "michellemwangim@gmail.com",
      client_phone: "0700562291",
      company_name: "Sensei",
      client_location: "MasaiMara",
      preferred_contact_method: "Email",
      category: "Technical Issue",
      platform_service_product: "Service",
      severity: "Critical",
      issue_description: "this is the details of the issue / task",
    },
    {
      client_name: "Michelle Mwangi",
      client_email: "michellemwangim@gmail.com",
      client_phone: "0700562291",
      company_name: "Sensei",
      client_location: "MasaiMara",
      preferred_contact_method: "Email",
      category: "Technical Issue",
      platform_service_product: "Service",
      severity: "Critical",
      issue_description: "this is the details of the issue / task",
    },
  ];
  const [taskListItems, setTaskListItems] = useState([]);

  useEffect(() => {
    setTaskListItems(tasksListData);
  }, []);

  const data = {
    taskListItems,
    setTaskListItems,
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        <DataContext.Provider value={data}>{children}</DataContext.Provider>
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          draggable
          pauseOnHover
          theme="dark"
        />
      </body>
    </html>
  );
}
